# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 564cd7aaf3b71b360659df6986649a61ce44ed45d7d9e453ea1494a6ecb73fc7083d09f34501ee4932be3a3eca7b213d0882ae22f080fb8566b1757f16a6d852

test:
  secret_key_base: 74d636d9be00ae9f752eb0c4a57e46bb4154dad751b5797a1e64c757cc0e456b7ce9758cbd3024c750fcdf5aac6f3230cbd26479756cb09fdab970db0e0448cf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
